# Generated by Django 3.1 on 2020-09-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0011_auto_20200917_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
