# Generated by Django 3.1 on 2020-09-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0014_auto_20200923_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='photo',
            field=models.ImageField(upload_to='file'),
        ),
    ]
