# Generated by Django 3.1 on 2020-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0016_auto_20200923_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_title', models.CharField(max_length=200)),
                ('vote', models.PositiveIntegerField(blank=True, default=0)),
                ('voters', models.ManyToManyField(to='Happ.Doctor')),
            ],
        ),
    ]
