# Generated by Django 3.1 on 2020-10-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0017_discussionvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionvote',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='discussionvote',
            name='voters',
        ),
        migrations.CreateModel(
            name='DiscussionWithVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.PositiveIntegerField(blank=True, default=0)),
                ('dis_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Happ.discussionvote')),
                ('voters', models.ManyToManyField(to='Happ.Doctor')),
            ],
        ),
    ]
