# Generated by Django 3.1 on 2020-10-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0019_auto_20201020_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionwithvote',
            name='voter',
        ),
        migrations.AddField(
            model_name='discussionwithvote',
            name='voters',
            field=models.ManyToManyField(to='Happ.Doctor'),
        ),
    ]
