# Generated by Django 3.1 on 2020-10-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0022_highdistitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highdistitle',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Happ.discussionwithvote'),
        ),
    ]
