# Generated by Django 3.1 on 2020-10-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0023_auto_20201026_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighDisTitle',
        ),
    ]
