# Generated by Django 3.1 on 2020-10-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0024_delete_highdistitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighDisTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.PositiveIntegerField(default=0)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Happ.discussionvote')),
            ],
        ),
    ]
