# Generated by Django 3.1 on 2020-10-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0025_highdistitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surv_title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyWithVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.PositiveIntegerField(blank=True, default=0)),
                ('surv_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Happ.surveyvote')),
                ('voters', models.ManyToManyField(to='Happ.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='HighSurTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.PositiveIntegerField(default=0)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Happ.surveyvote')),
            ],
        ),
    ]
