# Generated by Django 3.1 on 2020-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0027_newscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pin',
            field=models.CharField(default='_none_', max_length=6),
        ),
    ]
