# Generated by Django 3.1 on 2020-12-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0028_appointment_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
    ]
