# Generated by Django 3.1 on 2021-01-02 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0029_auto_20201226_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
