# Generated by Django 3.1 on 2021-01-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0035_auto_20210119_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
    ]
