# Generated by Django 3.1 on 2021-01-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0036_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profession',
        ),
    ]
