# Generated by Django 3.1 on 2021-01-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0037_remove_doctor_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Happ.profession'),
        ),
    ]
