# Generated by Django 3.1 on 2021-01-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0038_doctor_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
