# Generated by Django 3.1 on 2021-01-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0039_profession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirm',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
