# Generated by Django 3.1 on 2021-01-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0040_appointment_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloody_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marial_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
