# Generated by Django 3.1 on 2021-01-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0041_auto_20210128_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
