# Generated by Django 3.1 on 2021-01-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0042_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bloody_type',
            new_name='blood_type',
        ),
    ]
