# Generated by Django 3.1 on 2021-01-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Happ', '0044_auto_20210128_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
